name: Release Packages

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Verify:
    name: Verify Main Branch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Verify Main Branch
        run: |
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "‚ùå Error: This workflow can only be run from the main branch"
            exit 1
          fi

  Setup:
    name: Setup Workspace
    needs: Verify
    uses: ./.github/workflows/setup-workspace.yaml

  release:
    name: Release Packages
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Job
        uses: ./.github/actions/setup-job

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
