name: Create Release Version PR
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Version PR Title'
        default: 'Release new versions'
        required: false

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Verify:
    name: Verify Main Branch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Verify Main Branch
        run: |
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "‚ùå Error: This workflow can only be run from the main branch"
            exit 1
          fi

  Setup:
    name: Setup Workspace
    needs: Verify
    uses: ./.github/workflows/setup-workspace.yaml

  Version:
    name: Create Version PR
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Job
        uses: ./.github/actions/setup-job
        with:
          skip-build: 'true'

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: ${{ inputs.title }}
          version: pnpm run changelog:apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
